### ISSUE TITLE
map and test-map errors

### ISSUE THREAD

**Issue by chris-gomes** [melina7890/AI-part2#10]
In the test-map file:
- on line 7, it says "exit" is undefined (probably need "#include <stdlib.h>")
- on line 159, it says "test_pop" is undefined

Also, on lines 30, 49, and 66 in map.h, the function arguments should take in "object*" not "object". Can you also include "#pragma once" on line 1 of the map.h file.

Thank you!

**Comment by elehman16** [comment]
Good catch! Thanks!
