### ISSUE TITLE
Having a Pair is implementation detail

### ISSUE THREAD

**Issue by anuj-modi** [melina7890/AI-part2#11]
Related to #7, I suggest you remove the `pair.h` file as per this on Piazza: https://piazza.com/class/k51bluky59n2jr?cid=317_f3

>Q: What if there is already an implementation in the spec? 
>A: Let the spec team know that if they don't remove it, they will lose points. Further, they need to purge it from the history. git rm is not nearly enough. Also, please write up this incident as a part of your report.

**Comment by elehman16** [comment]
I agree to a certain extent, but they state that: "You have to negotiate with the spec team, which classes to add, or which method signatures to change." The professors are extremely vague here... If people want to use another class, then we must add it, and add tests for it.

**Comment by elehman16** [comment]
I asked on Piazza, and there is a very vague zone of what is an implementation and what is not. I removed it just to be safe...
