### ISSUE TITLE
Implementation of `in` within tests

### ISSUE THREAD

**Issue by panzer** [melina7890/AI-part2#14]
A few things:
1. `bool in(Objects** ol, Object* o)`

`Objects` is not defined, I believe you meant `Object`

2. `ol[i]` cannot be compared to the character '\0'... I think you meant `nullptr` (but keep reading)

3. Iterating through the array until `nullptr` is reached is undefined behavior in CwC.
There is no guarentee the array of pointers will terminate with a nullptr. I recommend passing a length to this `in` function

**Comment by elehman16** [comment]
Whoops! Thanks and good catch. I tested '\0' on an online C compiler, and it actually worked. I don't write C code (and don't plan to ever write any in the future after this class), so I am totally in the dark and realistically have no idea what I'm doing. But, good suggestion, and we *hopefully* patched it! Please raise another issue if something doesn't look right!

**Comment by sudopluto** [comment]
im pretty sure '\0' ---(int cast)---> 0 == nullptr, pretty funny tbh, had us scratching our head for a bit
