### ISSUE TITLE
How will customers know the length of `keys()` and `values()` returned arrays?

### ISSUE THREAD

**Issue by panzer** [melina7890/AI-part2#15]
There is currently no defined way for callers of `keys(...)` and `values(...)` to know the length of the returned array

**Comment by elehman16** [comment]
You can use the size function in the map class. The length of the keys and values should align properly with the size of the map (this is implied). Let me know if this works (so I can close this issue).

**Comment by panzer** [comment]
Ok that makes sense. Thanks
