### ISSUE TITLE
Copy method impossible without another constructor

### ISSUE THREAD

**Issue by saifshaikh48** [melina7890/AI-part2#18]
Hi, we are not able to create a copy of a Map if there is no constructor that takes in anything.
Preferably the constructor will look something like this: `Map( Object * keys, Object * values) {...}` or `Map(Map m) {...}`
Please add this into your spec.

**Comment by elehman16** [comment]
You do not need a constructor for this functionality.

**Comment by panzer** [comment]
You may add any constructor or helper methods you need.

https://piazza.com/class/k51bluky59n2jr?cid=362
