### ISSUE TITLE
Memory leaks in test_keys and test_values

### ISSUE THREAD

**Issue by panzer** [melina7890/AI-part2#21]
All calls to `map->keys()` or `map->values()` should eventually `delete` the returned `Object **`.

One bad usage as an example:
```
t_true(in(map->values(), s1, 2));
```

**Comment by elehman16** [comment]
Hmmm... I agree for writing code, but I am not sure about testing (in that you need to plug all memory leaks), since returning frees everything. I will fix it, but if you know about standard practice, feel free to comment and let me know.
