### ISSUE TITLE
Test objects should be deleted after tests are run

### ISSUE THREAD

**Issue by favorable-mutation** [melina7890/AI-part2#24]
Currently, the objects created for use in the tests are not deleted after use (e.g. o1, s1, etc.). Please update the main function of the tests to delete these objects after the tests are run, to allow downstream teams to check for memory errors in our implementations. Thanks!

**Comment by elehman16** [comment]
Pretty sure that you can ignore any errors valgrind gives on those. Return releases everything anyway. It's more of a style thing if anything. Might change it later if I have time.
