### ISSUE TITLE
Repo name must be lowercase

### ISSUE THREAD

**Issue by saifshaikh48** [melina7890/AI-part2#28]
The makefile given by the professors requires lowercase repository names.
Please go to settings and update this.

**Comment by elehman16** [comment]
Are you sure that this is the case??? We got our Makefile to work on other people's repo (i.e. https://github.com/mlanotte1998/SoftDevApi). Just to make sure I'm on the same page as you, you want our repo to be 'AI-part2' to 'ai-part2'?

**Comment by saifshaikh48** [comment]
To be honest this issue was opened because someone opened a similar one on our spec repo so assumed this was the case
(We have not tried running the make file yet using your url)

**Comment by elehman16** [comment]
I would say that it's probably fine as is... I think using https://github.com/melina7890/ai-part2/ works the same so... I don't know what the other people are talking about. Maybe post on Piazza if you have troubles.
