### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by barthch** [melina7890/AI-part2#8]
In test.cpp there are no delete statements. It is unclear which objects "own" each object. That is if an object is passed into the Map and Map is deleted should the object be deleted too? or when the object is passed should the Object be copied (then object would need a copy constructor). 

Also For get, keys, values, pop, and pop_item, who owns what is returned value. Do we expect the user to delete the returned object of not?

**Comment by elehman16** [comment]
Added some delete statements, and commented. Did not delete strings at the end because the memory is released at the end.  Also added a new test to imply what functionality deleting a Map does.

**Comment by barthch** [comment]
I assume that clear() does not delete the objects in the map. 

As for not deleting the strings because the memory is released at the end. yes that is a function of the Operating System. However it is still good practice to pair all "new" statements with a "delete" statement. I might suggest allocating them on the stack instead, or initializing them in the main function and deleting them in the main function.
