### ISSUE TITLE
standardize object and string

### ISSUE THREAD

**Issue by az0977776** [melina7890/AI-part2#9]
Can we try to just use the definitions of string and object that Jan provided us:
https://piazza.com/class/k51bluky59n2jr?cid=330

https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by elehman16** [comment]
I agree that this should be done, but what I'm hoping is that none of our tests use any specific features from Jan's code (hopefully)! For example, we try to only use the .equals methods. So hopefully our string implementation does not _conflict_ with other people's code. Let me know if I'm missing something here! Thanks for the question :)

**Comment by elehman16** [comment]
Alright. So even though it's SUPER vague about what we should do, Prof. Vitek said on Piazza: _"You have to be able to compile all data structures together -- they will be used in the same project! The best way forward is to get the spec teams to agree on some set of features for for the basic classes."_ So as long as we don't have methods that other people don't use (for object and string class), everything should be good. Also, waiting on an official response for: https://piazza.com/class/k51bluky59n2jr?cid=332. Let me know if I can close this issue.
